### ISSUE TITLE
TradeMe traffic watch

### ISSUE THREAD

**Issue by rimutaka** [mVentory/utils#1]
TradeMe has site stats API
http://developer.trademe.co.nz/api-reference-2/catalogue-methods/retrieve-site-statistics/ or https://api.trademe.co.nz/v1/SiteStats.xml

Which returns this

```
<SiteStats>
<MembersOnline>81169</MembersOnline>
<ActiveMembers>3728631</ActiveMembers>
<ActiveListings>3144831</ActiveListings>
<AverageTimeSpent>8 minutes</AverageTimeSpent><AverageVisitorsPerDay>878497</AverageVisitorsPerDay><BusiestDayOfWeek>Sunday</BusiestDayOfWeek>
<ReportMonthAndYear>June 2015</ReportMonthAndYear>
<ReportSource>Nielsen Online</ReportSource>
</SiteStats>
```

only the first 3 are live

```
<MembersOnline>81169</MembersOnline>
<ActiveMembers>3728631</ActiveMembers>
<ActiveListings>3144831</ActiveListings>
```

if we collect the data in 15 minute intervals we should have some interesting stats to show on mventory.com.
### Implementation
1. Run a node.js script on a schedule that will call the stats api, retrieve the 3 params and store them in a google spreadsheet.
2. Create a JS script for reading the spreadsheet and drawing a chart of the data as a zoomable line chart using google charts api.

The node.js script can be hosted on google apps engine or AWS lambda.

**Comment by rimutaka** [comment]
Carl create this spreadsheet https://docs.google.com/spreadsheets/d/1PvLp6O5NLeXZW00l79PXL0Zqcy3ysAocmBmX7tKTPPU/edit#gid=0 and will be using https://developers.google.com/chart/interactive/docs/gallery/linechart#dual-y-charts to equalise number of members (10^6), auctions (10^7) and members online (10^4) on the same chart.

**Comment by rimutaka** [comment]
Early prototype: http://jsfiddle.net/cubski/crhazL7o/1/

The chart doesn't look 100%. 
It would be good to add line smoothing and show a 7day interval in a single graph, zoomable.
Let's look into it after deployment.

**Comment by cubski** [comment]
@rimutaka OK. I'll update the charts. The reason I put them in separate charts is that the values are far apart, and when plotted in a single chart you can barely see the line chart values so it doesn't look good. I could use dual y-axis chart but we have 3 data sets. Let me know what you think.

**Comment by rimutaka** [comment]
@cubski 1 - posted comments to your initial commit, 2 - switched the code to https://docs.google.com/spreadsheets/d/1RMcibAPjuPim7N_MUFdVeYqiN_ngroNrQzsHy6VDwB4/edit#gid=0, but ran into 403 error with google.

Can you tell me how to authorise a service_account to access a single document?
Add it to the instructions.

Let's get the data collection working and then worry about the charts.

**Comment by rimutaka** [comment]
Thanx @

**Comment by rimutaka** [comment]
Thanx @cubski. The code is live. 

We will quickly run into a problem with too much data in the table for the graph if we keep loading the entire spreadsheet into a JS table. This will be a separate issue when we actually run into it.

The graphs will need work to make the data more presentable, but let's collect some more first.
