### ISSUE TITLE
Timezone offset

### ISSUE THREAD

**Issue by rimutaka** [mVentory/utils#2]
The time is logged in UTC. It is meaningless in the local context. We need to log it in NZT.
The offset is UTC + 13hrs, but will change with day saving hrs on/off in NZ. We can just update the script when it changes again.

@cubski - can you take care of this problem?

**Comment by cubski** [comment]
@rimutaka Will fix the timezone settings. Will also write a function that fixes the datetimes of the existing records in the spreadsheet.

**Comment by rimutaka** [comment]
Just fix the timezone in the node.js function. I can fix the existing data in the spreadsheet with copy-pasting.

**Comment by cubski** [comment]
Understood.

**Comment by cubski** [comment]
Fix committed.

**Comment by rimutaka** [comment]
All done. Pls, get in touch.
